name: C/C++ CI

on: [push]

jobs:
  build:hello

    runs-on: ubuntu-latest
    
    steps:
    - name: make
      run: make
    - name: make check
      run: ./hello
    - name: make distcheck
    -  run: make distcheck
